title: Freedgo Design:专注在线绘图工具,ER模型设计
subtitle: 一款在线制图软件
description: 轻松、快速、协作地创建各种专业图表。 freedgo Design 是一个多种类型图表的在线绘制软件，让您创建 阿里云架构图 腾讯云架构图 Oracle云架构图 AWS系统部署图 软件架构图, UML，BPMN，ERD，流程图，UX设计图,ANT DESIGN，思维导图，图表。立即开始免费试用
keywords: 在线绘图工具，在线图表工具，图表工具，图表解决方案，在线图表制造商，在线图表创建者，在线uml工具，图表软件，在线阿里云部署图工具，在线AWS部署图工具，在线腾讯云部署图工具，流程图工具，工程电气在线设计，平面图设计，UX设计，信息图表制造商，图表制造商，信息图表软件， 图表软件，业务在线设计，在线图表编辑器
author: 南京裕奥软件科技有限公司
language: en
timezone: UTC

url: https://www.freedgo.com
root: /public
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: baidu_url_submitter
highlight:
  enable: true
  line_number: false

disqus_shortname: freedgo-design
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  applicationID: SE79HO1X34
  apiKey: e3bd7a46ce95447cea05b2470e6ea075
  indexName: algolia-freedgo
twitter: changsy2017
github: csy2013/freedgo
baidu_url_submit:
  count: 1000
  host: www.freedgo.com
  token: e9avp4LG2sK9Gj9F
  path: baidu_urls.txt