title: Freedgo Design:专注在线绘图工具,ER模型设计
subtitle: 一款在线制图软件
description: 轻松、快速、协作地创建各种专业图表。 freedgo Design 是一个多种类型图表的在线绘制软件，让您创建 阿里云架构图 腾讯云架构图 Oracle云架构图 AWS系统部署图 软件架构图, UML，BPMN，ERD，流程图，UX设计图,ANT DESIGN，思维导图，图表。立即开始免费试用
keywords: 在线绘图工具，在线图表工具，图表工具，图表解决方案，在线图表制造商，在线图表创建者，在线uml工具，图表软件，在线阿里云部署图工具，在线AWS部署图工具，在线腾讯云部署图工具，流程图工具，工程电气在线设计，平面图设计，UX设计，信息图表制造商，图表制造商，信息图表软件， 图表软件，业务在线设计，在线图表编辑器
author: 南京裕奥软件科技有限公司
language: en
timezone: UTC

url: https://www.freedgo.com
root: /public
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
theme: navy
deploy:
  type: baidu_url_submitter
highlight:
  enable: true
  line_number: false

disqus_shortname: freedgo-design
#google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  applicationID: SE79HO1X34
  apiKey: e3bd7a46ce95447cea05b2470e6ea075
  indexName: algolia-freedgo
twitter: changsy2017
github: csy2013/freedgo
hexo_submit_urls_to_search_engine:
  submit_condition: count #链接被提交的条件，可选值：count | period 现仅支持count
  count: 10 # 提交最新的10个链接
  period: 900 # 提交修改时间在 900 秒内的链接
  google: 0 # 是否向Google提交，可选值：1 | 0（0：否；1：是）
  bing: 1 # 是否向bing提交，可选值：1 | 0（0：否；1：是）
  baidu: 1 # 是否向baidu提交，可选值：1 | 0（0：否；1：是）
  txt_path: submit_urls.txt ## 文本文档名， 需要推送的链接会保存在此文本文档里
  baidu_host: https://www.freedgo.com ## 在百度站长平台中注册的域名
  baidu_token: xxxxx ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  bing_host: https://www.freedgo.com ## 在bing站长平台中注册的域名
  bing_token: xxxxx ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  google_host: https://www.freedgo.com ## 在google站长平台中注册的域名
  google_key_file: Project.json #存放google key的json文件，放于网站根目录（与hexo _config.yml文件位置相同），请不要把json文件内容直接发布在公众仓库里!